USE WAREHOUSE VADSON;
USE DATA BASE VAD;
USE SCHEMA BOB;



SELECT
    *
FROM
    jomashop js
WHERE
    js.DATE > '2024-01-09'
    AND js.ITEM_NUMBER IN (SELECT ITEM_NUMBER FROM ITEMS)
ORDER BY js.DATE_ADDED DESC;